version: "3.9"
services:
  app:
    build: .
    ports: 
      - "8501:8501"
    command: "streamlit run Home.py"

  api:
    build: .
    ports: 
      - "9600:9600"
    command: "python3 -m api.main"
